! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.0.2 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Monitor.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(16) :: SPC_NAMES = (/ &
     'CH4                             ','CO                              ','CO2                             ', & ! index 1 - 3
     'COfromCH4                       ','COfromNMVOC                     ','CO2fromOH                       ', & ! index 4 - 6
     'Dummy                           ','CH3CCl3                         ','DummyMCF                        ', & ! index 7 - 9
     'PCO                             ','LCO                             ','LCH4                            ', & ! index 10 - 12
     'FixedOH                         ','FixedCl                         ','DummyCH4                        ', & ! index 13 - 15
     'DummyNMVOC                      ' /) ! index up to 16

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(9) :: EQN_NAMES = (/ &
     '    CH4 + FixedOH --> CO + COfromCH4 + PCO + LCH4                                                   ', & ! index 1
     '    CH4 + FixedCl --> Dummy + LCH4                                                                  ', & ! index 2
     '     CO + FixedOH --> CO2 + CO2fromOH + LCO                                                         ', & ! index 3
     '       DummyNMVOC --> CO + COfromNMVOC + PCO                                                        ', & ! index 4
     'CH3CCl3 + FixedOH --> DummyMCF                                                                      ', & ! index 5
     '              CH4 --> Dummy + LCH4                                                                  ', & ! index 6
     '         DummyCH4 --> CO + PCO                                                                      ', & ! index 7
     '               CO --> CO2 + CO2fromOH + LCO                                                         ', & ! index 8
     '          CH3CCl3 --> DummyMCF                                                                      ' /) ! index up to 9

  CHARACTER(LEN=32), PARAMETER, DIMENSION(3) :: FAM_NAMES = (/ &
     'PCO                             ','LCO                             ','LCH4                            ' /) ! index up to 3

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
